import {design} from './design-config';
import {Button as UIButton} from 'antd';
import React,{useState,useEffect,useRef} from 'react';
import {ClinicFlower,CaretRight,CaretDown,MagnifyingGlass,TextAa,Question,List,Lock,CheckCircle} from './icons';
import {Ctx} from './ui';
import {ClinicTheme} from './Theme';
import {DemoCenter} from './DemoCenter';
import {menus,people,initialRx,initialHerbs,initialCalls} from './data';
import {Today,Prescriptions,Stock,Calendar,Patients,Calls,Forms,Messages,Business,Settings} from './pages';
import {Leave,initialLeaves} from './leave';
import {Overlay,Tablet} from './overlays';
export function App(){
 const [demoMenu,setDemoMenu]=useState(false),[demoActive,setDemoActive]=useState(false),[screenKey,setScreenKey]=useState(0),demoSeed=useRef(null);
 const [leaves,setLeaves]=useState(initialLeaves),[compact,setCompact]=useState(()=>window.innerWidth<=1000);
 useEffect(()=>{const query=window.matchMedia('(max-width:1000px)');const sync=()=>setCompact(query.matches);query.addEventListener('change',sync);return()=>query.removeEventListener('change',sync)},[]);
 const [route,setRoute]=useState(location.hash.slice(1)||'today'),[overlay,setOverlay]=useState(null),[toast,setToast]=useState(''),[side,setSide]=useState(false),[font,setFont]=useState(()=>Number(localStorage.getItem('ondam-font')||18)),[motion,setMotion]=useState(()=>localStorage.getItem('ondam-motion')!=='off'),[role,setRole]=useState('원장'),[rx,setRx]=useState(initialRx),[herbs,setHerbs]=useState(initialHerbs),[patients,setPatients]=useState(people),[calls,setCalls]=useState(initialCalls),[delivered,setDelivered]=useState(1),[events,setEvents]=useState([{id:1,day:'2026-09-25',name:'김○○',rx:1042,state:'재료 대기',time:'미지정'},{id:2,day:'2026-09-25',name:'박○○',rx:1044,state:'탕전 예정',time:'14:00'},{id:3,day:'2026-09-26',name:'정○○',rx:1043,state:'탕전 예정',time:'미지정'}]),[costs,setCosts]=useState([{name:'약재 매입',kind:'재료비',amount:6800000},{name:'인건비',kind:'직원',amount:8200000},{name:'임대료',kind:'반복 비용',amount:2500000},{name:'운영비',kind:'기타',amount:1000000}]),[rules,setRules]=useState([false,false,false]),[formCount,setFormCount]=useState(2),[reviewed,setReviewed]=useState([]),[starts,setStarts]=useState({}),[formAnswers,setFormAnswers]=useState(null);
 useEffect(()=>{const fn=()=>{setRoute(location.hash.slice(1)||'today');setSide(false);setOverlay(null);window.scrollTo(0,0)};window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[]);
 useEffect(()=>{document.documentElement.style.fontSize=font+'px';document.documentElement.dataset.motion=motion?'on':'off';localStorage.setItem('ondam-font',String(font));localStorage.setItem('ondam-motion',motion?'on':'off')},[font,motion]);
 useEffect(()=>{if(toast){const id=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(id)}},[toast]);
 useEffect(()=>{function key(e){if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setOverlay({type:'search'})}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 const nav=r=>{setSide(false);setOverlay(null);if(location.hash==='#'+r){setRoute(r);window.scrollTo(0,0)}else location.hash=r};
 const captureDemoState=()=>structuredClone({leaves,route,font,motion,role,rx,herbs,patients,calls,delivered,events,costs,rules,formCount,reviewed,starts,formAnswers});
 if(!demoSeed.current)demoSeed.current={...captureDemoState(),font:18,motion:true,role:'원장'};
 const restoreDemoState=s=>{const d=structuredClone(s);for(const [key,set] of Object.entries({leaves:setLeaves,font:setFont,motion:setMotion,role:setRole,rx:setRx,herbs:setHerbs,patients:setPatients,calls:setCalls,delivered:setDelivered,events:setEvents,costs:setCosts,rules:setRules,formCount:setFormCount,reviewed:setReviewed,starts:setStarts,formAnswers:setFormAnswers}))set(d[key]);setToast('');setScreenKey(n=>n+1);nav(d.route);};
 const resetDemoState=route=>restoreDemoState({...demoSeed.current,route});
 const app={demoActive,setDemoActive,captureDemoState,restoreDemoState,resetDemoState,leaves,setLeaves,route,nav,open:setOverlay,close:()=>setOverlay(null),notify:setToast,font,setFont,motion,setMotion,role,setRole,rx,setRx,herbs,setHerbs,patients,setPatients,calls,setCalls,delivered,setDelivered,events,setEvents,costs,setCosts,rules,setRules,formCount,setFormCount,reviewed,setReviewed,starts,setStarts,formAnswers,setFormAnswers};
 const current=menus.find(x=>x[0]===route)||menus[0], Page={today:Today,prescriptions:Prescriptions,stock:Stock,calendar:Calendar,patients:Patients,calls:Calls,forms:Forms,messages:Messages,business:Business,settings:Settings,leave:Leave}[route]||Today;
 return <ClinicTheme font={font} motion={motion}><Ctx.Provider value={app}>{route==='tablet'?<Tablet key={screenKey}/>:<div className="app"><a className="skip" href="#main" onClick={e=>{e.preventDefault();document.getElementById('main').focus()}}>본문으로 바로가기</a>{side&&<UIButton type="text" className="nav-scrim" aria-label="메뉴 닫기" onClick={()=>setSide(false)}/>}<aside id="main-navigation" inert={compact&&!side} className={'sidebar '+(side?'open':'')}><a className="brand" href="#today"><span className="brand-symbol" aria-hidden="true"><ClinicFlower size={28}/></span><span>온담 업무실</span></a><p className="brand-sub">우리 한의원의 하루</p><div className="nav-caption">우리의 워크스페이스</div><nav aria-label="주요 메뉴">{menus.filter(([id])=>id!=='business'||role==='원장').map(([id,name,Icon])=><a key={id} href={'#'+id} aria-current={route===id?'page':undefined} className={route===id?'selected':''} onClick={()=>setSide(false)}><Icon size={24} weight={route===id?'duotone':'regular'}/><span>{name}</span>{id==='business'&&role!=='원장'&&<Lock size={16}/>}</a>)}</nav><UIButton type="text" className="profile" onClick={()=>setOverlay({type:'role'})}><span className="initial">{role==='원장'?'한':role==='데스크'?'A':'B'}</span><span><small>시연 역할</small><b>{role} {role==='원장'?'한승재':role==='데스크'?'직원 A':'직원 B'}</b></span><CaretRight/></UIButton></aside><div className="workspace"><header className="topbar"><UIButton type="text" className="icon-btn mobile-menu" aria-label="메뉴 열기" aria-expanded={side} aria-controls="main-navigation" onClick={()=>setSide(true)}><List size={26}/></UIButton><div className="breadcrumb">업무 <span>/</span> <b>{current[1]}</b></div><UIButton type="text" className="global-search" onClick={()=>setOverlay({type:'search'})}><MagnifyingGlass size={22}/><span>환자, 처방, 메뉴 검색</span><kbd>⌘ K</kbd></UIButton><div className="top-actions"><UIButton className="demo-launch" disabled={demoActive} onClick={()=>setDemoMenu(true)}>자동 시연</UIButton><UIButton type="text" className="text-control" aria-label="글자·화면" onClick={()=>setOverlay({type:'display'})}><TextAa size={24}/><span>글자·화면</span><CaretDown size={15}/></UIButton><UIButton type="text" className="help-btn" aria-label="도움말" onClick={()=>setOverlay({type:'help'})}><Question size={25}/><span>도움말</span></UIButton></div></header><main id="main" tabIndex="-1"><div className="view" key={route+screenKey}><Page/></div><footer className="page-footer"><span>온담 업무실 <b>{design.label}</b></span><span>디자인 검토용 · 가상 데이터 · 새로고침 시 업무 데이터 초기화</span></footer></main></div></div>}{overlay&&<Overlay key={overlay.type+String(overlay.id||'')} data={overlay}/>}<DemoCenter open={demoMenu} onClose={()=>setDemoMenu(false)}/><div className={'toast '+(toast?'show':'')} role="status"><CheckCircle size={22}/>{toast}</div></Ctx.Provider></ClinicTheme>
}
