import React,{createContext,useContext,useEffect,useRef,useId} from 'react';
import {MagnifyingGlass,X,Warning} from '@phosphor-icons/react';
import {Button,Input,Select,DatePicker,Segmented,Tag,Alert,Card,Table,Calendar as AntCalendar,Empty as AntEmpty,Drawer,Modal as AntModal} from 'antd';
import dayjs from 'dayjs';
export const Ctx=createContext(null); export const useApp=()=>useContext(Ctx);
export const tone=s=>/부족|임박|상담|실패|보류/.test(s)?'rose':/대기|확인 필요|부재/.test(s)?'amber':/완료|확정|정상|성공/.test(s)?'green':/문진|작성|검토/.test(s)?'purple':'blue';
export function Badge({children,color}){return <Tag variant="filled" className={'badge '+(color||tone(String(children)))}>{children}</Tag>}
export function Btn({children,onClick,primary=false,icon:Icon,small=false,type='button',...props}){return <Button type={primary?'primary':'default'} htmlType={type} className={`btn ${primary?'primary':''} ${small?'small':''}`} icon={Icon?<Icon size={21}/>:undefined} onClick={onClick} {...props}>{children}</Button>}
export function Empty({text='조건에 맞는 내역이 없어요.',detail='다른 검색어나 필터로 다시 확인해 주세요.'}){return <AntEmpty className="empty" image={<MagnifyingGlass size={34}/>} description={<><h3>{text}</h3><p>{detail}</p></>}/>}
export function Panel({title,sub,action,children,className=''}){return <Card className={'panel '+className} styles={{body:{padding:0}}}>{title&&<div className="panel-head"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>{action}</div>}{children}</Card>}
export function Tabs({items,value,onChange}){return <Segmented className="tabs" options={items} value={value} onChange={onChange} size="large"/>}
export function Search({value,onChange,placeholder='이름 또는 번호로 검색'}){useDemoInput(placeholder,onChange);return <Input className="search" prefix={<MagnifyingGlass size={21}/>} allowClear aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/>}
export function PageTitle({title,desc,children}){return <div className="page-title"><div><h1>{title}</h1><p>{desc}</p></div><div className="actions">{children}</div></div>}
export function DataTable({heads,children}){const rows=React.Children.toArray(children).filter(React.isValidElement).map((r,i)=>({key:r.key||i,cells:React.Children.toArray(r.props.children).map(c=>c.props?.children)}));const columns=heads.map((h,i)=>({title:h,key:String(i),render:(_,r)=>r.cells[i]}));return <Table className="data-table" columns={columns} dataSource={rows} pagination={false} scroll={{x:'max-content'}} size="middle" locale={{emptyText:null}}/>}
export function Field({label,children}){const id=useId();useDemoInput(label,v=>children.props?.onChange?.({target:{value:v}}));let control=children;if(React.isValidElement(children)){const p=children.props,change=v=>p.onChange?.({target:{value:v}});if(children.type==='input'){if(p.type==='date')control=<DatePicker {...p} type={undefined} id={id} aria-label={label} format="YYYY-MM-DD" value={p.value?dayjs(p.value):null} defaultValue={undefined} minDate={p.min?dayjs(p.min):undefined} allowClear={false} onChange={(_,s)=>change(s)} style={{width:'100%'}}/>;else control=<Input {...p} id={id} aria-label={label}/>;}else if(children.type==='textarea')control=<Input.TextArea {...p} id={id} aria-label={label}/>;else if(children.type==='select'){const options=React.Children.toArray(p.children).map(c=>({value:c.props.value??c.props.children,label:c.props.children}));control=<Select {...p} children={undefined} id={id} aria-label={label} options={options} defaultValue={p.defaultValue??(p.value===undefined?options[0]?.value:undefined)} onChange={change} style={{width:'100%'}}/>;}}return <div className="field"><label htmlFor={id}>{label}</label>{control}</div>}
export function Notice({children,type='blue'}){return <Alert className={'notice '+type} type={type==='rose'?'error':type==='amber'?'warning':type==='green'?'success':'info'} showIcon icon={<Warning size={21}/>} description={children}/>}
export function KV({items}){return <dl className="kv">{items.map(([k,v],i)=><div key={k+i}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>}
export function Modal({title,children,wide=false,drawer=true,onClose}){const a=useApp(),returnFocus=useRef(document.activeElement);useEffect(()=>()=>{requestAnimationFrame(()=>{if(!document.querySelector('[role="dialog"]')){const el=returnFocus.current?.isConnected?returnFocus.current:document.getElementById('main');el?.focus()}})},[]);const closeIcon=<X size={23} aria-label="닫기"/>;const common={open:true,title:<h2>{title}</h2>,destroyOnHidden:true,keyboard:true};return drawer?<Drawer {...common} rootClassName="clinic-drawer" size={wide?'min(50rem,100vw)':'min(32rem,100vw)'} closable={{placement:'end',closeIcon}} onClose={onClose} mask={{closable:true}} focusable={{trap:true,focusTriggerAfterClose:true}} styles={{body:{padding:'1.3rem 1.5rem 1.8rem'},header:{padding:'1rem 1.4rem'}}}>{children}</Drawer>:<AntModal {...common} className="clinic-modal" centered footer={null} width="min(31rem,calc(100vw - 1rem))" onCancel={onClose} closeIcon={closeIcon} styles={{body:{maxHeight:'76dvh',overflowY:'auto',paddingTop:'.7rem'}}}>{children}</AntModal>}

export function MonthCalendar({month,renderDay,onDayClick}){return <div className="calendar-scroll"><AntCalendar className="clinic-calendar" value={dayjs(new Date(2026,month,month===8?25:1))} headerRender={()=>null} onSelect={(date,info)=>{if(info.source==='date')onDayClick?.(date.format('YYYY-MM-DD'))}} cellRender={(date,info)=>info.type==='date'?renderDay(date.format('YYYY-MM-DD')):info.originNode}/></div>}

// Automated presentations use the same controlled input callbacks as manual input.
function useDemoInput(label,onChange){const a=useApp();useEffect(()=>{if(!a?.demoActive)return;const input=e=>{if(e.detail.label===label)onChange?.(e.detail.value)};window.addEventListener('ondam-demo-input',input);return()=>window.removeEventListener('ondam-demo-input',input)},[a?.demoActive,label,onChange]);}
